name: Github Unravel Pipeline

on:
  pull_request:
    types:
      - opened

jobs:
  auto_pr_comments:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Run unravel github client script
        run: |
          python unravel_github_client.py

        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          UNRAVEL_URL: ${{ secrets.UNRAVEL_URL }}
          UNRAVEL_JWT_TOKEN: ${{ secrets.UNRAVEL_JWT_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
